In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

Filtering

In [5]:
filt = df['last']=='Doe' # cant use filter as a variable since it is a built in function
df[filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [6]:
df[df['last']=='Doe'] # same as above

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [7]:
df.loc[filt] # same as above (loc is used to access a group of rows and columns by labels or a boolean array) boolean array is used here

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [8]:
df.loc[filt, 'email'] # same as above but only email column (advantage of using loc)

1    JaneDoe@email.com
2    JohnDoe@email.com
Name: email, dtype: object

Other filtering methods & (and), | (or)

In [13]:
filte = (df['last']=='Doe') & (df['first']=='John') # the & is used to combine two filters which should be in brackets
df.loc[filte]

  first last              email
2  John  Doe  JohnDoe@email.com

In [15]:
fil = (df['last']=='Schafer') | (df['first']=='John')
df.loc[fil]

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@email.com

Opposite of filter ~ (not)

In [16]:
fil = (df['last']=='Schafer') | (df['first']=='John')
df.loc[~fil] # ~ is used to negate the filter (opposite of the filter)

  first last              email
1  Jane  Doe  JaneDoe@email.com