In [1]:
people = {
    'first': ['Corey', 'Jane', 'John'], 
    'last': ['Schafer', 'Doe', 'Doe'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
df['first'] + ' ' + df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: object

## Adding Column

In [6]:
df['full_name'] = df['first'] + ' ' + df['last'] # cant use dot notation to create new column
df

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [7]:
# same as above (using apply)
df['name'] = df.apply(lambda x: x['first'] + ' ' + x['last'], axis='columns')
df

   first     last                    email      full_name           name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe       John Doe

## Removing Column

In [8]:
df.drop(columns=['first','last','name'], inplace = True)

In [9]:
df

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

## Splitting a string

In [21]:
df['full_name'].str.split(' ', expand=True) # expand=True will return a dataframe instead of a series

0    [Corey, Schafer]
1         [Jane, Doe]
2         [John, Doe]
4                 NaN
5                 NaN
Name: full_name, dtype: object

In [11]:
df[['first','last']] = df['full_name'].str.split(' ', expand=True)
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

## Adding and removing rows of data

adding a single row

In [ ]:
new_row = pd.DataFrame([{'first':'Tony'}])
df = pd.concat([df,new_row], ignore_index=True) # ignore_index=True will ignore the index of the new row
df 
# NaN : Not a Number (missing value)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

## Concatenating other data frames

In [13]:
people = {
    'first': ['Tony', 'Steve'], 
    'last': ['Stark', 'Rogers'], 
    'email': ['Ironman@email.com', 'Cap@email.com']
}

In [14]:
df2 = pd.DataFrame(people)

In [15]:
df2

   first    last              email
0   Tony   Stark  Ironman@email.com
1  Steve  Rogers      Cap@email.com

In [16]:
df =pd.concat([df,df2], ignore_index=True)

In [17]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4        Ironman@email.com            NaN   Tony    Stark
5            Cap@email.com            NaN  Steve   Rogers

## Removing rows

In [18]:
df.drop(index=3, inplace=True)
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
4        Ironman@email.com            NaN   Tony    Stark
5            Cap@email.com            NaN  Steve   Rogers

In [19]:
# using filter method
filt = df['last'] == 'Doe'
df.drop(index=df[filt].index)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
4        Ironman@email.com            NaN   Tony    Stark
5            Cap@email.com            NaN  Steve   Rogers

In [20]:
# using filter method (same as above)
df.drop(index=df[df['last']=='Doe'].index)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
4        Ironman@email.com            NaN   Tony    Stark
5            Cap@email.com            NaN  Steve   Rogers